-- Execute conectado ao banco api_fundamentos.
-- A API deve ter sido iniciada ao menos uma vez para que a tabela produtos exista.

-- Relacionamento 1:N: uma categoria pode possuir vários produtos.
CREATE TABLE IF NOT EXISTS categorias (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(80) NOT NULL UNIQUE,
    descricao VARCHAR(255)
);

ALTER TABLE produtos
    ADD COLUMN IF NOT EXISTS categoria_id BIGINT;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_produtos_categorias'
    ) THEN
        ALTER TABLE produtos
            ADD CONSTRAINT fk_produtos_categorias
            FOREIGN KEY (categoria_id)
            REFERENCES categorias (id)
            ON UPDATE CASCADE
            ON DELETE SET NULL;
    END IF;
END
$$;

CREATE INDEX IF NOT EXISTS idx_produtos_categoria_id
    ON produtos (categoria_id);

-- Relacionamento 1:1: cada produto possui no máximo um registro de estoque.
CREATE TABLE IF NOT EXISTS estoques (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produto_id BIGINT NOT NULL UNIQUE,
    quantidade INTEGER NOT NULL DEFAULT 0 CHECK (quantidade >= 0),
    estoque_minimo INTEGER NOT NULL DEFAULT 0 CHECK (estoque_minimo >= 0),
    atualizado_em TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_estoques_produtos
        FOREIGN KEY (produto_id)
        REFERENCES produtos (id)
        ON UPDATE CASCADE
        ON DELETE CASCADE
);

-- Cadastro independente de fornecedores.
CREATE TABLE IF NOT EXISTS fornecedores (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(120) NOT NULL,
    documento VARCHAR(30) NOT NULL UNIQUE,
    email VARCHAR(160),
    ativo BOOLEAN NOT NULL DEFAULT TRUE
);

-- Relacionamento N:N: um produto pode ter vários fornecedores e vice-versa.
-- A tabela associativa também guarda atributos próprios da relação.
CREATE TABLE IF NOT EXISTS produtos_fornecedores (
    produto_id BIGINT NOT NULL,
    fornecedor_id BIGINT NOT NULL,
    codigo_no_fornecedor VARCHAR(60),
    custo NUMERIC(12, 2) CHECK (custo >= 0),
    prazo_dias INTEGER CHECK (prazo_dias >= 0),
    PRIMARY KEY (produto_id, fornecedor_id),
    CONSTRAINT fk_produtos_fornecedores_produto
        FOREIGN KEY (produto_id)
        REFERENCES produtos (id)
        ON UPDATE CASCADE
        ON DELETE CASCADE,
    CONSTRAINT fk_produtos_fornecedores_fornecedor
        FOREIGN KEY (fornecedor_id)
        REFERENCES fornecedores (id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT
);

CREATE INDEX IF NOT EXISTS idx_produtos_fornecedores_fornecedor
    ON produtos_fornecedores (fornecedor_id);
